- hosts: "{{hostName}}"

  vars_prompt:

  - name: ansible_ssh_pass
    prompt: Remote user password
    private: yes

  - name: hostName
    prompt: 'host(s):'
    private: no

  become: yes


  tasks:

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
